simple_public_sale/core/urls.py
from django.urls import path, re_path


from core.views import *

urlpatterns = [

    path('', list_all_events, name='list-all-events'),
    re_path('assistir/evento/(?P<group_id>.+)', watch_event, name='watch-event'),
    path('todos/participantes', get_participante_names, name='todos-participantes'),
    re_path('gerenciar/evento/(?P<evento_id>[0-9]+)', manage_event, name='manage-event'),
    re_path('gerenciar/arrematadores/(?P<evento_id>[0-9]+)', list_gift_finishers, name='event-finishers'),
    re_path('gerenciar/arrematador/resumo/(?P<evento_id>[0-9]+)', finisher_summary, name='finisher-summary'),
    re_path('gerenciar/desfazer/movimento/(?P<movimento_id>.+)', undo_arrematador_lance, name='undo-movement-prenda'),
    re_path('gerenciar/arrematar/prenda/(?P<prenda_id>[0-9]+)/(?P<evento_id>[0-9]+)', arrematar_prenda, name='arrematar-prenda'),
    re_path('gerenciar/prenda/desfazer/arremate/(?P<prenda_id>[0-9]+)/(?P<evento_id>[0-9]+)', undo_arrematar_prenda, name='desfaz-arrematar-prenda'),
    re_path('gerenciar/prenda/desfazer/doacao/(?P<prenda_id>[0-9]+)/(?P<evento_id>[0-9]+)', undo_donation, name='undo-donation'),
    re_path('gerenciar/doar/prenda/(?P<prenda_id>[0-9]+)', donate_prenda,
            name='donate-prenda'),
    re_path('gerenciar/focar/prenda/(?P<evento_id>[0-9]+)', focus_prenda,
            name='focus_prenda'),

]

simple_public_sale/simple_public_sale/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static

from core.views import send_message

urlpatterns = [
    path('admin', admin.site.urls),

    path('', include('core.urls') ),

]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns+= static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += re_path(r'^__debug__/', include(debug_toolbar.urls)),

simple_public_sale/core/models.py
from django.core.exceptions import ValidationError
from django.db import models, IntegrityError
from django.db.models import Max
from django.db.models.signals import pre_save, post_save, post_delete, pre_delete
from django.dispatch import receiver
from twisted.protocols.amp import Decimal

from channels_core.models import GrupoEvento
from core.utils import send_to_evento

import copy
# class Doador(models.Model):
#     nome_doador = models.CharField(max_length=100)
#     apelido_doador = models.CharField(max_length=100)
#     cpf_cnpj_doador = models.CharField(max_length=14)
#     def __str__(self):
#         return self.nome_doador
class ParticipanteManager(models.Manager):
    def get_by_natural_key(self, apelido):
        return self.get(nome=apelido)

class Participante(models.Model):
    apelido = models.CharField(max_length=100,null=True,blank=True,unique=True,db_index=True)
    nome = models.CharField(max_length=100,null=True,blank=True)
    cpf_cnpj = models.CharField(max_length=14,null=True,blank=True)
    rg = models.CharField(max_length=50,null=True,blank=True)
    endereco = models.CharField(max_length=200,null=True,blank=True)

    objects=ParticipanteManager()
    def __str__(self):
        return self.apelido

    def natural_key(self):
        return (self.apelido)
    def total_pagar_evento(self,evento_id):
        prendas=Prenda.objects.filter(arrematador=self,evento__pk=evento_id)
        total=0
        for prenda in prendas:
            total+=prenda.get_movimento_arremate().valor
        print(total)
        return total
class Evento(models.Model):
    nome = models.CharField(max_length=100)
    data = models.DateTimeField(null=True,blank=True)
    url_image = models.ImageField(upload_to='imagens')
    grupo = models.OneToOneField(GrupoEvento, null=True, blank=True, on_delete=models.CASCADE)
    def __str__(self):
        return self.nome
    def is_online(self):
        return self.grupo.online
    
class TipoPrenda(models.Model):
    nome = models.CharField(max_length=100,default='',null=True,blank=True)
    descricao = models.CharField(max_length=100)
    url_image = models.ImageField(upload_to='tipos/imagens',null=True,blank=True)
    def __str__(self):
        return self.nome

class Caracteristica(models.Model):
    caracteristica = models.CharField(max_length=60)
    descricao = models.CharField(max_length=150)
    def __str__(self):
        return self.caracteristica

class Prenda(models.Model):
    doador = models.ForeignKey(Participante, on_delete=models.CASCADE)
    valor_inicial = models.DecimalField(decimal_places=2, max_digits=8,default=0)
    tipo_prenda = models.ForeignKey(TipoPrenda, on_delete=models.CASCADE)
    evento = models.ForeignKey(Evento, on_delete=models.CASCADE)
    # arrematada = models.BooleanField(default=False)
    arrematador = models.ForeignKey(Participante,on_delete=models.CASCADE,related_name="arrematador",null=True,blank=True,default=True)
    url_image = models.ImageField(upload_to='prendas/imagens', null=True, blank=True)
    parent = models.OneToOneField('Prenda', on_delete=models.CASCADE, blank=True, null=True,verbose_name='Doação de')
    caracteristicas = models.ManyToManyField(Caracteristica,through='CaracteristicaPrenda')
    def __str__(self):
        return '%s [doado por: %s]'%(self.tipo_prenda.nome,self.doador.apelido)
    
    def get_prenda_clone(self):

        if not self.arrematador:
            raise ValidationError("Esta Prenda ainda nao foi arrematada")


        prenda = Prenda()


        prenda.doador = self.get_arrematador()
        prenda.valor_inicial = self.valor_inicial
        prenda.evento = self.evento
        prenda.tipo_prenda = self.tipo_prenda
        prenda.url_image = self.url_image
        prenda.arrematador = None
        prenda.parent=self
        prenda.save()


        for caracteristica_prenda in self.caracteristicaprenda_set.all():
            new_caracteristica_prenda=copy.copy(caracteristica_prenda)
            new_caracteristica_prenda.pk=None
            new_caracteristica_prenda.prenda_id=prenda.id
            new_caracteristica_prenda.save()

        return prenda

    def get_arrematador(self):
        movimentos=self.movimento_set.all()
        if self.arrematador and movimentos:
            print("oioi")
            return movimentos.order_by('-valor').first().arrematador

        return None
    def get_arrematador_atual(self):
        movimentos=self.movimento_set.all()
        if movimentos:
            print("oioi")
            return movimentos.order_by('-valor').first().arrematador

        return None
    def is_doada(self):
        return Prenda.objects.filter(parent=self).count()

    def get_movimento_arremate(self):
        if self.arrematador:

            return self.movimento_set.all().order_by('-valor').first()

        return None
    def get_maior_movimento(self):
        movimentos=self.movimento_set.all()
        if movimentos:

            return movimentos.order_by('-valor').first()
        return None
    def last_three_movements(self):
        return self.movimento_set.all().order_by("-data_ocorrencia", "-valor")[0:3]
    def get_doador_primario(self):
        doador_primario=None
        prenda = self
        while(True):
            if prenda.parent==None:
                return prenda.doador

            prenda=prenda.parent
    def get_caracteristicas_json(self):
        caracteristicas=[]
        for caracteristica in self.caracteristicaprenda_set.all():
            valor=caracteristica.valor
            chave = caracteristica.caracteristica.caracteristica
            caracteristica = {"caracteristica":chave,"valor":valor}
            caracteristicas.append(caracteristica)

        return caracteristicas
class CaracteristicaPrenda(models.Model):
    prenda = models.ForeignKey(Prenda,on_delete=models.CASCADE)
    caracteristica = models.ForeignKey(Caracteristica,on_delete=models.CASCADE)
    valor = models.CharField(max_length=100)
    class Meta:
        unique_together=('prenda','caracteristica')
    def __str__(self):
        return "%s - %s"%(self.caracteristica.caracteristica, self.prenda.tipo_prenda.nome)

class Movimento(models.Model):
    data_ocorrencia = models.DateField(auto_now=True,editable=False)
    arrematador = models.ForeignKey(Participante, on_delete=models.CASCADE)
    valor = models.DecimalField(decimal_places=2, max_digits=8)
    prenda = models.ForeignKey('Prenda', on_delete=models.CASCADE)

    def __str__(self):
        return "%s - %s : R$ %s"%(self.arrematador.apelido,self.prenda.tipo_prenda.nome,self.valor)
    def send_to_stream(self):
        if self.prenda.evento.is_online():
            prenda = self.prenda
            send_to_evento(prenda=prenda)
            print("Stream Atualizada")
        else:
            print("Stream Offline")
        return False

@receiver(pre_save, sender=Evento)
def post_save_evento(sender,instance, **kwargs):
    assert isinstance(instance, Evento)
    if not instance.grupo:
        grupo=GrupoEvento()
        grupo.nome = instance.nome
        grupo.evento=instance
        grupo.online=True
        grupo.save()
        print(grupo)
        instance.grupo=grupo


@receiver(pre_save, sender=Movimento)
def pre_save_movimento(sender,instance, **kwargs):
    assert isinstance(instance, Movimento)

    if instance.prenda.arrematador:
        raise ValidationError("Não é possível enviar mais lances, esta prenda já foi arrematada.")

    maior_movimento= instance.prenda.get_maior_movimento()
    if maior_movimento and float(instance.valor) <= float(maior_movimento.valor):
        raise ValidationError("Este lance é menor que o maior lance atual!")

@receiver(post_save, sender=Movimento)
def post_save_movimento(sender,instance, **kwargs):
    assert isinstance(instance, Movimento)

    instance.send_to_stream()

@receiver(post_delete, sender=Movimento)
def pre_delete_movimento(sender,instance, **kwargs):
    assert isinstance(instance, Movimento)
    if instance.prenda.arrematador:
        raise ValidationError("Não é possível remover lances de uma prenda arrematada.")

@receiver(post_delete, sender=Movimento)
def post_delete_movimento(sender,instance, **kwargs):
    assert isinstance(instance, Movimento)
    instance.send_to_stream()

# @receiver(pre_save, sender=Prenda)
# def pre_delete_movimento(sender,instance, **kwargs):
#     assert isinstance(instance, Prenda)
#     if instance.parent.is_doada():
#         raise ValidationError("Esta Prenda ja foi doada anteriormente2")
@receiver(pre_save, sender=Participante)
def pre_save_arrematador(sender,instance, **kwargs):
    assert isinstance(instance, Participante)
    instance.apelido=instance.apelido.upper()

@receiver(pre_save, sender=CaracteristicaPrenda)
def pre_save_caracteristica_prenda(sender,instance, **kwargs):
    assert isinstance(instance, CaracteristicaPrenda)
    if(instance.prenda.caracteristicaprenda_set.count()>=3):
        raise IntegrityError("Cada prenda tem um limite de 3 caracteristicas.")

@receiver(pre_save, sender=Prenda)
def pre_save_prenda(sender,instance, **kwargs):
    assert isinstance(instance, Prenda)
    if instance.parent:
        print(instance.parent.arrematador)
        if not instance.parent.arrematador:
            raise ValidationError("Uma prenda doada precisa vir de outra arrematada.")


    if not instance.arrematador and Prenda.objects.filter(parent=instance) and instance.pk:

        raise ValidationError("Esta prenda foi doada, para desfazer o arremate é necessário primeiro desfazer a doação.")

    if instance.arrematador and not instance.movimento_set.all():
        raise ValidationError(
            "Esta prenda não possui nenhum lance.")

    if instance.movimento_set.all():

        instance.movimento_set.first().send_to_stream()

simple_public_sale/core/forms.py
from decimal import Decimal
from django import forms
from django.core.exceptions import ValidationError

from .models import Movimento, Prenda



class MovimentoForm(forms.Form):
    nome_arrematador = forms.CharField(label="Arrematador", max_length=120)
    valor_arremate = forms.FloatField(label="Valor")

    def __init__(self, *args, **kwargs):
        self.data = kwargs.pop('data', None)
        super(MovimentoForm, self).__init__(*args, **kwargs)




    def clean_valor_arremate(self):
        cleaned_data = super().clean()
        valor_arremate = cleaned_data.get('valor_arremate')

        movimento_anterior = Movimento.objects.filter(prenda__pk=self.data['prenda_id']).order_by('-id')
        print(self.data)

        if movimento_anterior:
            print("passou")
            movimento_anterior=movimento_anterior[0]

            if Decimal(valor_arremate) <= movimento_anterior.valor:
                msg = "Valor do arremate não pode ser menor ou igual do que o valor atual da prenda!"
                raise forms.ValidationError(msg)
        else:
            prenda = Prenda.objects.get(id = self.data['prenda_id'])
            print(prenda)

            if Decimal(valor_arremate) <= prenda.valor_inicial:
                msg = "Valor do arremate não pode ser menor ou igual do que o valor inicial da prenda!"
                raise forms.ValidationError(msg)

simple_public_sale/templates/base.html
<!DOCTYPE html>

{% load static %}

<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Listagem de eventos</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/jquery-confirm.min.css' %}">
    <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/1.10.16/css/dataTables.bootstrap4.min.css"/>

    <style>
        .autocomplete-suggestions {
            border: 1px solid #999;
            background: #FFF;
            overflow: auto;
        }

        .autocomplete-suggestion {
            padding: 2px 5px;
            white-space: nowrap;
            overflow: hidden;
        }

        .autocomplete-selected {
            background: #F0F0F0;
        }

        .autocomplete-suggestions strong {
            font-weight: normal;
            color: #3399FF;
        }

        .autocomplete-group {
            padding: 2px 5px;
        }

        .autocomplete-group strong {
            display: block;
            border-bottom: 1px solid #000;
        }
    </style>
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
    <div class="navbar-header">
        <a class="navbar-brand" href="#">Simple Public Sale</a>
    </div>
</nav>
<main>
    <div class="container">
    {% block content %}{% endblock %}
    </div>

</main>
<footer class="page-footer blue center-on-small-only">

    <div class="footer-copyright">
        <div class="container-fluid">
            Todos os direitos reservados © 2018 Copyright: Allan Lúcio Correia, Eduardo Lúcio Correia e João Paulo
            Ferreira da Silva

            <div class="float-right">
                Software open source
                <a class="ml-2" href="https://github.com/allanufal/simple-public-sale" target="_blank"> <img
                        src="{% static 'img/github-logo.png' %}" alt="github"></a>
            </div>
        </div>
    </div>

</footer>


<script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'js/jquery.scrollTo.min.js' %}"></script>
<script src="{% static 'js/popper.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/mdb.min.js' %}"></script>
<script src="{% static 'js/jquery-confirm.min.js' %}"></script>
<script src="{% static 'js/jquery.autocomplete.js' %}"></script>
<script src="{% static 'js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'js/dataTables.bootstrap4.min.js' %}"></script>

{% block scripts %}
{% endblock %}
{#<script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>#}
{#<script src="https://cdn.datatables.net/1.10.16/js/dataTables.bootstrap4.min.js"></script>#}

{% for message in messages %}
    <script>
        var tipo = "{{ message.tags }}";
        var type = "green";
        switch (tipo) {
            case "error":
                type = "red";
                break;
            case "success":
                type = "green";
                break;
            case "warning":
                type = "orange";
                break;
            case "info":
                type = "blue";
                break;
        }
        $.confirm({
            title: 'Aviso!',
            content: '{{ message }}',
            type: 'red',
            typeAnimated: true,
            buttons: {
                tryAgain: {
                    text: 'Prosseguir',
                    btnClass: 'btn-green',
                    action: function () {
                    }
                },

            }
        });

    </script>
{% endfor %}




</body>
</html>

simple_public_sale/templates/list_all_events.html
{% extends 'base.html' %}
{% block content %}
    <div class="container mt-4">
        {% if eventos %}
            <div class="row">
                {% for evento in eventos %}
                    <div class="col-12 col-sm-6 col-md-4 col-lg-4 col-xl-3">
                        <div class="card mt-3">
                            <img class="img-fluid" src="{{ evento.url_image }}" alt="card-image">

                            <div class="card-body">
                                <h5 class="card-title"> {{ evento.nome.capitalize }} </h5>
                                <h6 class="card-subtitle mb-2 text-muted"> {{ evento.data | date:'d/m/Y' }}</h6>


                                <a title="Assistir Evento Ao vivo" class="card-link" href="{% url 'watch-event' evento.grupo.id %}"> <i class="material-icons">remove_red_eye</i></a>
                                <a title="Gerenciar evento" class="card-link float-right" href="{% url 'manage-event' evento.id %}"> <i class="material-icons">settings</i></a>
                                <a title="Resumo geral de todos os arrematadores" class="card-link" href="{% url 'event-finishers' evento.id %}"> <i class="material-icons">view_list</i></a>
                                <a title="Filtro por Arrematador" class="card-link" href="{% url 'finisher-summary' evento.id %}"> <i class="material-icons">filter_list</i></a>
                            </div>
                        </div>

                    </div>


                {% endfor %}
            </div>

        </div>
    {% else %}
            <h4 style="text-align: center"><b>Não existem eventos cadastrados.</b></h4>
    {% endif %}



    <script>
        function openWebSocket(username, group_id) {
            socket = new WebSocket("ws://" + window.location.host + "/chat/?username=" + username + "&group_id=" + group_id);
            socket.onmessage = function (e) {
                console.log(e.data);
            };
            socket.onopen = function () {
                socket.send("hello world");
            };
            // Call onopen directly if socket is already open
            if (socket.readyState == WebSocket.OPEN) socket.onopen();
        }


    </script>
{% endblock %}

simple_public_sale/templates/manage_event.html
{% extends 'base.html' %}
{% block content %}





        <br>
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="{% url 'list-all-events' %}">Eventos</a></li>
                <li class="breadcrumb-item active">{{ evento.nome }}</li>
            </ol>
        </nav>

        <h4>Prendas</h4>
        <!-- List group -->

        <div id="accordion" role="tablist">
            {% for prenda in evento.prenda_set.all %}
                <div class="card">

                    <div class="card-header" role="tab" id="heading_{{ forloop.counter }}">
                        <span title="Clique para exibir esta prenda ao vivo!" data-prenda='{{ prenda.pk }}' class="badge red float-left mr-2 live-focus {% if not prenda.get_arrematador_atual %} disabled {% endif %}">Live </span>

                        <h5 class="float-left" style="display: inline-block;">
                            <a data-toggle="collapse" href="#id_prenda_{{ prenda.pk }}" role="button"
                               aria-expanded="true"
                               aria-controls="collapseOne">
                                {{ prenda.tipo_prenda.nome }} - {{ prenda.doador.apelido }}
                            </a>
                        </h5>

                        {% if prenda.arrematador %}
                            <span class="badge black float-right mr-2">Arrematada </span>


                        {% elif prenda.get_arrematador_atual %}
                                <span class="badge green float-right mr-2">Em andamento </span>
                        {% else %}
                                <span class="badge grey float-right mr-2">Na fila</span>
                        {% endif %}



                        {% if prenda.parent %}
                            <span class="badge purple float-right mr-2">Doada </span>
                            <!--<small></small>-->
                        {% endif %}

                        <br>

                        {% if prenda.is_doada %}
                            <a href="{% url 'undo-donation' prenda_id=prenda.id evento_id=evento.pk %}"
                               class="btn btn-warning float-right btn-sm">
                                Desfazer Doação
                            </a>
                        {% endif %}

                        {% if prenda.arrematador != None %}
                            {% if prenda.is_doada == False %}
                                <a href="{% url 'donate-prenda' prenda_id=prenda.id %}"
                                   class="btn btn-warning float-right btn-sm">
                                    Doar
                                </a>
                            {% endif %}
                        {% endif %}


                    </div>
                    <div class="col-md-6 offset-6">

                        <div class="row offset-6">

                        </div>
                    </div>


                    <div id="id_prenda_{{ prenda.pk }}" class="{% if prenda_selected.pk == prenda.pk %}collapse show{% else %}collapse{% endif %}" role="tabpanel"
                         aria-labelledby="headingOne"
                         data-parent="#accordion">
                        <div class="card-body">

                            <form method="post">
                                {% csrf_token %}
                                <div class="row">

                                    <div class="col-8">
                                        <h4>Adicione um novo lance:</h4>
                                        <div class="md-form">
                                            <label for="{{ form.nome_arrematador.id_for_label }}">Arrematador</label>
{#                                            {{ form.nome_arrematador }}#}
                                            <input autofocus type="text" name="nome_arrematador" id="" class="autocomplete-input"/>
                                        </div>
                                        <div class="md-form">


                                            <label for="{{ form.valor_arremate_id_for_label }}">Valor</label>
                                            {{ form.valor_arremate }}
                                        </div>
                                        <input type="hidden" name="prenda_id" value="{{ prenda.pk }}">
                                        <input type="hidden" name="group_id" value="{{ evento.grupo_id }}">
                                        <button type="submit" class="btn btn-primary" name="btn-enviar" {% if prenda.is_doada or prenda.arrematador != None %} disabled {% endif %}>Enviar Lance</button>

                                        {% if prenda.arrematador %}
                                            <a href="{% url 'desfaz-arrematar-prenda'  prenda_id=prenda.pk evento_id=evento.id %}"
                                               class="btn btn-warning float-right"><i
                                                    class="material-icons"></i>Desfazer Arremate</a>
                                        {% else %}
                                            <a href="{% url 'arrematar-prenda'  prenda_id=prenda.pk evento_id=evento.id %}"
                                               class="btn btn-danger float-right"><i
                                                    class="material-icons"></i>Arrematar</a>
                                        {% endif %}


                                    </div>

                                    <div class="col-4">
                                        <h5>Últimos três lances:</h5>
                                        <ul class="list-group">
                                            {% for move in prenda.last_three_movements %}
                                                <li class="list-group-item">
                                                    {{ move.arrematador }} (
                                                    <span class="text-primary monetary-value">{{ move.valor }}</span> )
                                                    {% if prenda.is_doada or prenda.arrematador != None %}
                                                        <a href="#"
                                                           class="btn-sm btn-danger float-right disabled" ><i
                                                                class="material-icons">undo</i></a>
                                                    {% else %}
                                                        <a href="{% url 'undo-movement-prenda' movimento_id=move.id %}"
                                                           class="btn-sm btn-danger float-right" ><i
                                                                class="material-icons">undo</i></a>
                                                    {% endif %}
                                                </li>
                                            {% endfor %}
                                        </ul>
                                    </div>
                                </div>


                            </form>


                        </div>
                    </div>

                </div>




            {% endfor %}

        </div>





{% endblock %}

{% block scripts %}
<script>
        $(document).ready(function () {
            $(window).scrollTo('#id_prenda_{{ prenda_selected.pk }}',200);

            $('.live-focus').click(function () {
                var prenda_id = $(this).data('prenda');
                var data = {prenda_id:prenda_id,csrfmiddlewaretoken: '{{ csrf_token }}'};
               $.ajax({
                  type: "POST",
                  url: '/gerenciar/focar/prenda/{{ evento.pk }}',
                  data: data,
                  success:function (res) {
                      console.log(res);
                  }

                });
            });

            $('.autocomplete-input').autocomplete({
                serviceUrl: '/todos/participantes',
                onSelect: function (suggestion) {
                    {#alert('You selected: ' + suggestion.value + ', ' + suggestion.data);#}
                }
            });

            $(".monetary-value").each(function () {
                console.log($(this).text());
                var num = Number($(this).text());
                $(this).text(num.toLocaleString('pt-BR', {style: 'currency', currency: 'BRL'}));
            })
        })
    </script>

    {% if form.errors %}
        {% for valor_arremate in form %}
            {% for error in valor_arremate.errors %}
                {{ valor_arremate.errors }}
                <script>
                $(document).ready(function () {
                    $.confirm({
                        title: 'Aviso!',
                        content: '{{ error }}',
                        type: 'red',
                        typeAnimated: true,
                        buttons: {
                            tryAgain: {
                                text: 'Prosseguir',
                                btnClass: 'btn-green',
                                action: function () {
                                    $('.collapse').collapse("show");
                                    $('#id_valor_arremate').val("");
                                    $('#id_valor_arremate').focus();
                                }
                            },

                        }
                    });
                });
                </script>

            {% endfor %}
        {% endfor %}

    {% endif %}
{% endblock %}

simple_public_sale/templates/simple_chat_send.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
    <form method="post">
        <input type="text" name="message">
        {% csrf_token %}
        <input type="submit">
    </form>

<script>
    socket = new WebSocket("ws://" + window.location.host + "/chat/?username=allan");
socket.onmessage = function(e) {
    console.log(e.data);
}
socket.onopen = function() {
    socket.send("hello world");
}
// Call onopen directly if socket is already open
if (socket.readyState == WebSocket.OPEN) socket.onopen();

</script>
</body>
</html>